# Generated by Django 4.1.3 on 2022-11-19 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the Team.', max_length=25)),
                ('group', models.CharField(help_text='Qualifying group', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateField(verbose_name='Match Date')),
                ('phase', models.CharField(choices=[('GM', 'Group Matches'), ('16', 'Qualifying'), ('QF', 'Quarter-Final'), ('SF', 'Semi-Final'), ('F', 'Final')], max_length=300)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='stats.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='stats.team')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.IntegerField()),
                ('wins', models.FloatField()),
                ('looses', models.FloatField()),
                ('draws', models.FloatField()),
                ('country1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country1', to='stats.team')),
                ('country2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country2', to='stats.team')),
            ],
        ),
    ]
