# Generated by Django 4.1.3 on 2022-11-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_rename_team_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='name',
            field=models.CharField(help_text='The name of the Team.', max_length=128),
        ),
    ]
