# Generated by Django 4.1.3 on 2022-11-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_alter_teams_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='phase',
            field=models.CharField(max_length=300),
        ),
    ]
