# Generated by Django 4.1.3 on 2022-11-20 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_alter_matches_phase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matches',
            old_name='publication_date',
            new_name='date',
        ),
    ]
