# Generated by Django 4.1.3 on 2022-11-20 12:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_rename_publication_date_matches_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Match Date')),
                ('phase', models.CharField(max_length=300)),
                ('team1_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('team2_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.RenameField(
            model_name='history',
            old_name='country1',
            new_name='team1',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='country2',
            new_name='team2',
        ),
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
        migrations.DeleteModel(
            name='Matches',
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='stats.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='stats.team'),
        ),
    ]
