# Generated by Django 4.1.3 on 2022-11-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_fantasy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(help_text='Student Name', max_length=128)),
                ('year', models.CharField(help_text='What Class', max_length=5)),
            ],
        ),
    ]
