# Generated by Django 4.1.3 on 2022-11-20 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stats', '0009_remove_fantasy_class_year_remove_fantasy_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fantasy',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
